### ISSUE TITLE
Scala classes not being generated, although pointing to Avro schema with setting

### ISSUE THREAD

**Issue by Sahand1993** [sbt/sbt-avro#117]
I'm trying to use this repo sbt-avro in a Scala project to generate a Scala class from an Avro schema.

Here is the project structure:

```
multi-tenant/
    build.sbt
    project/
        plugins.sbt
    src/
        main/
            resources/
                avro/
                    Measurement.avsc
            scala/
                com.mycom.multitenant/
                    Producer

```
And here is the build.sbt (note that I try to point the sbt-avro plugin to the location of my Avro source files using the avroSource setting):

```
version := "1.0"

lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "com.mycom",
      scalaVersion := "2.12.15"
    )),
    name := "multi-tenant",
    avroSource := new File("src/main/resources/avro"),
  )

libraryDependencies += "org.apache.avro" % "avro" % "1.11.0"

```        

the plugins.sbt:
```

addSbtPlugin("com.github.sbt" % "sbt-avro" % "3.4.0")

// Java sources compiled with one version of Avro might be incompatible with a
// different version of the Avro library. Therefore we specify the compiler
// version here explicitly.
libraryDependencies += "org.apache.avro" % "avro-compiler" % "1.11.0"
```

When building in IntelliJ (top-right green hammer button), no sources get generated. I have also tried writing compile in the sbt console with the same result.

Here are some logs which appear when I first start up the sbt console in IntelliJ. It may contain some clues:

```
[info] welcome to sbt 1.5.8 (Oracle Corporation Java 11.0.11)
[info] loading global plugins from /home/sahand/.sbt/1.0/plugins
[info] loading settings for project multi-tenant-build from plugins.sbt,idea.sbt ...
[info] loading project definition from /home/sahand/multi-tenant/project
[warn] Unrecognized repository Scala Plugin Bundled Repository, ignoring it
[info] loading settings for project root from build.sbt ...
[info] set current project to multi-tenant (in build file:/home/sahand/multi-tenant/)
[warn] there's a key that's not used by any other settings/tasks:
[warn]  
[warn] * root / avroSource
[warn]   +- /home/sahand/multi-tenant/build.sbt:10
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] Defining Global / ideaPort
[info] The new value will be used by Compile / compile, Test / compile
[info] Reapplying settings...
[info] set current project to multi-tenant (in build file:/home/sahand/multi-tenant/)
```
Seems like the plugin cannot pick up the `avroSource` setting. Is this a bug, or am I using the plugin wrong?

**Comment by RustedBones** [comment]
Hi @Sahand1993 
I think the problem comes from the [scoping](https://www.scala-sbt.org/1.x/docs/Scopes.html#Scopes) of the `avroSource` setting. The values used by the plugins are: 
```sh
sbt> show Compile / avroSource
[info] ...../src/main/avro
sbt> show Test / avroSource
[info] ...../src/test/avro
```

Can you try to change the setting for:

```sbt
Complie / avroSource := resourceDirectory.value / "avro"
```

As for IntelliJ, you'll have to run `avroGenerate` before compiling in the IDE

**Comment by Sahand1993** [comment]
Hi, I hope I understood your instructions correctly, here's what I did:

I removed target/

I changed the build.sbt to:
```

version := "1.0"

lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "com.datareply",
      scalaVersion := "2.12.15"
    )),
    name := "multi-tenant",
    Compile / avroSource := resourceDirectory.value / "avro"
  )

libraryDependencies += "org.apache.avro" % "avro" % "1.11.0"
``` 

and I ran avroGenerate in the sbt shell, followed by compile. None of the calls led to generated Scala Avro classes.

Also, I see the following when loading sbt changes in IntelliJ. Seems like the avroSource setting is not properly defined?

```
/usr/lib/jvm/jdk-11.0.11/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Didea.managed=true -Dfile.encoding=UTF-8 -Didea.installation.dir=/snap/intellij-idea-community/352 -jar /home/sahand/.local/share/JetBrains/IdeaIC2021.3/Scala/launcher/sbt-launch.jar
[info] welcome to sbt 1.5.8 (Oracle Corporation Java 11.0.11)
[info] loading global plugins from /home/sahand/.sbt/1.0/plugins
[info] loading settings for project multi-tenant-build from plugins.sbt ...
[info] loading project definition from /home/sahand/multi-tenant/project
[info] loading settings for project root from build.sbt ...
Reference to undefined setting:
resourceDirectory from Compile / avroSource (/home/sahand/multi-tenant/build.sbt:10)
Did you mean Compile / resourceDirectory ?
at sbt.internal.util.Init.Uninitialized(Settings.scala:419)
at sbt.internal.util.Init.Uninitialized$(Settings.scala:406)
at sbt.Def$.Uninitialized(Def.scala:24)
at sbt.internal.util.Init.delegate(Settings.scala:313)
at sbt.internal.util.Init.delegate$(Settings.scala:275)
at sbt.Def$.delegate(Def.scala:24)
at sbt.internal.util.Init.compiled(Settings.scala:200)
at sbt.internal.util.Init.compiled$(Settings.scala:187)
at sbt.Def$.compiled(Def.scala:24)
at sbt.internal.util.Init.makeWithCompiledMap(Settings.scala:217)
at sbt.internal.util.Init.makeWithCompiledMap$(Settings.scala:212)
at sbt.Def$.makeWithCompiledMap(Def.scala:24)
at sbt.internal.Load$.$anonfun$apply$5(Load.scala:263)
at sbt.internal.Load$.timed(Load.scala:1393)
at sbt.internal.Load$.apply(Load.scala:255)
at sbt.internal.Load$.defaultLoad(Load.scala:56)
at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
at sbt.Command$.process(Command.scala:189)
at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
at scala.Option.getOrElse(Option.scala:189)
at sbt.MainLoop$.process$1(MainLoop.scala:245)
at sbt.MainLoop$.processCommand(MainLoop.scala:278)
at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
at sbt.MainLoop$.next(MainLoop.scala:163)
at sbt.MainLoop$.run(MainLoop.scala:144)
at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
at sbt.io.Using.apply(Using.scala:27)
at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
at sbt.MainLoop$.runLogged(MainLoop.scala:42)
at sbt.StandardMain$.runManaged(Main.scala:218)
at sbt.xMain$.$anonfun$run$11(Main.scala:133)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at scala.Console$.withIn(Console.scala:230)
at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at scala.Console$.withOut(Console.scala:167)
at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at scala.Console$.withErr(Console.scala:196)
at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
at sbt.xMain$.withStreams$1(Main.scala:87)
at sbt.xMain$.run(Main.scala:121)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
at sbt.xMain.run(Main.scala:46)
at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
at xsbt.boot.Launch$.run(Launch.scala:149)
at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
at xsbt.boot.Launch$.launch(Launch.scala:159)
at xsbt.boot.Launch$.apply(Launch.scala:44)
at xsbt.boot.Launch$.apply(Launch.scala:21)
at xsbt.boot.Boot$.runImpl(Boot.scala:78)
at xsbt.boot.Boot$.run(Boot.scala:73)
at xsbt.boot.Boot$.main(Boot.scala:21)
at xsbt.boot.Boot.main(Boot.scala)
[error] Reference to undefined setting:
[error]
[error]   resourceDirectory from Compile / avroSource (/home/sahand/multi-tenant/build.sbt:10)
[error]      Did you mean Compile / resourceDirectory ?
[error]
[error] Use 'last' for the full log.

```

**Comment by RustedBones** [comment]
Seeing the [tests](https://github.com/sbt/sbt-avro/blob/de4bad70784238ce29fe0d802e09c821c150eb7d/src/sbt-test/sbt-avro/settings/build.sbt#L11), I also missed the scoping part on the `resourceDirectory`.

I would recommend to write the settings like this
```sbt
lazy val root = (project in file("."))
  .settings(
      organization := "com.datareply",
      name := "multi-tenant",
      scalaVersion := "2.12.15",
      version := "1.0",
      libraryDependencies += "org.apache.avro" % "avro" % "1.11.0",
      Compile / avroSource := (Compile / resourceDirectory).value / "avro"
  )
```

**Comment by Sahand1993** [comment]
So, I changed my build.sbt to this after your message, but still no Scala classes are generated:

```
version := "1.0"

lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "com.datareply",
      scalaVersion := "2.12.15"
    )),
    name := "multi-tenant",
    libraryDependencies += "org.apache.avro" % "avro" % "1.11.0",
    Compile / avroSource := (Compile / resourceDirectory).value / "avro"
  )
```

**Comment by RustedBones** [comment]
The plugin does not generate `scala` classes but `java` ones (this plugin is using the official `avro` java compiler).
Don't you have some generated java classes in `target/scala-2.12/src_managed/main/compiled_avro/` ?

**Comment by Sahand1993** [comment]
Sorry, I meant no classes get generated at all. Just to be clear, build.sbt looks like this now:

```
version := "1.0"

lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "com.datareply",
      scalaVersion := "2.12.15"
    )),
    name := "multi-tenant",
    libraryDependencies += "org.apache.avro" % "avro" % "1.11.0",
    Compile / avroSource := (Compile / resourceDirectory).value / "avro"
  )

```

And avro files are in `src/main/resources/avro`.

Nothing gets generated in `target/scala-2.12/src_managed/main/compiled_avro/`. In fact, `src_managed` isn't even created.

**Comment by Sahand1993** [comment]
I still think the setting isn't picked up. When I move the files to `src/main/avro`, even if I keep the `Compile / avroSource := (Compile / resourceDirectory).value / "avro"`, the source file is generated. So the setting seems to be ignored.

**Comment by RustedBones** [comment]
I double checked on my side that the setting is picked correctly.
Can you run `show Compile / avroSource` in `sbt` to make sure the config points to the right folder ?

**Comment by Sahand1993** [comment]
Sure, here you go:

```
[IJ]show Compile / avroSource
[info] /home/sahand/multi-tenant/src/main/resources/avro
[IJ]
```

**Comment by Sahand1993** [comment]
That is the correct path. Java class is still not being created, though.

**Comment by RustedBones** [comment]
Hey, sorry for the delay. I didn't think of something else to try.
Has this been solved on your side ?

**Comment by RustedBones** [comment]
Closing since not active. Feel free to re-open if support is still needed
